### ISSUE TITLE
Fehler in den Schaltern

### ISSUE THREAD

**Issue by eshopsrc** [noone2k/hm2500pub#2]
Schalter schalten nicht, sie lassen sich zwar clicken, schalten aber nicht den Status um und bleiben bei einem Reload nicht bestehen.

Was bewirkt "enable unknown Query (cmd30)" ??

ENHANCED: Enforce DOD | ON | Off   On
ENHANCED: enable Cell Query (cmd0F) | ON | Off   On
ENHANCED: enable unknown Query (cmd30) | OFF | Off   On
INTERNAL:DEBUG HEXDUMP
MQTT: opendtu - zero power | OFF

**Comment by noone2k** [comment]
meinst du nur die von dir geposteten schalter ? das funktioniert bei mir erstmal ...
diese schalter nutze ich momentan nur per webinterface zum testen. 
per mqtt habe ich das noch nicht probiert.

wenn du nur die geposteten meinst, gibt es einen widerspruch in deiner aussage:

"Schalter schalten nicht" und "bleiben bei einem Reload nicht bestehen." ...

bei einem RESTART ( nicht reload ) werden die auf sichere defaults gesetzt.
wobei das momentan überflüssig ist, wenn man ausgang 2 benutzt, statt 1.

diese cmd0F/cmd30 schalter sind dazu da, um die ble-verbindung etwas zu entlasen,
da die vermutung im raum stand'/steht, das die kisten überlastet sind, wenn zuviele befehle reinkommen.
das scheint momentan aber obsolete: seitdem ich kein wlan mehr an habe, schmiert die kiste nicht mehr ab.
bisher, also toi toi toi ...

"enable unknown Query (cmd30)" schaltet den befehl 0x30 an ( momentan glaube alle stunde einmal oder so ).
dieser befehl wird von der app gesendet, aber mit den antworten kann ich noch nichts anfangen.
deswegen "unknown query" ...

**Comment by eshopsrc** [comment]
Hm komisch, jetzt wo ich die Schalter oben im yaml auf off gestellt habe

 - switch.turn_off: switch_opendtu_limit
 - switch.turn_off: switch_enhanced_cmd0F
 - switch.turn_off: switch_enhanced_cmd30

geht es. Klicke ich auf den Schalter, wird der Status entsprechend gesetzt und übernommen.

Allerdings kommen weiterhin folgende Ausgaben im Log …


17:25:55	[W]	[script:060]	Script 'ble_process_cmd0F' is already running! (mode: single)
17:19:57	[W]	[ble_sensor:078]	Error reading char at handle 21, status=2
17:19:57	[W]	[ble_sensor:078]	Error reading char at handle 21, status=2
17:20:00	[W]	[script:060]	Script 'ble_process' is already running! (mode: single)
17:20:02	[W]	[script:060]	Script 'ble_process_cmd30' is already running! (mode: single)

**Comment by noone2k** [comment]
ist beim c&p was schief gelaufen ? die timestamps sind nicht in der richtigen reihenfolge ...
und kommt der fehler nur beim start oder wiederholt der sich laufend  ?

**Comment by eshopsrc** [comment]
Ja kann sein ich hab den vorher nicht sauber erwischt… jedes mal beim kopieren was der schon 1 Zeile weiter

Timestamps kannste weglassen, Abfolge der Meldungen ist richtig

**Comment by noone2k** [comment]
wiederholen sich andauernd die meldungen oder kommen die nur beim starten ... ?

**Comment by eshopsrc** [comment]
Nach dem Starten, dann läuft das ganze flüssig 5 - 10 Minuten und dann geht es los …

Ich hab den Verdacht das der ESP32 (Chinaklon) einen weg hat ...

**Comment by noone2k** [comment]
das es am chinaklon liegt, glaube ich erstmal nicht .. kann man zwar nicht ausschließen, aber die entsprechend fast alle dem gleich design ( das wird von espressif zur verfüpgung gestellt ).

habe mal ein commit gemacht, welches ggf. helfen könnte ...

**Comment by noone2k** [comment]
ich gehe mal davon aus, das das eigentliche problem gelöst ist, welches anscheinend keines war.
ich schließ dann mal ...

**Comment by eshopsrc** [comment]
ne ist noch offen, das ändern vom Board hat es nicht wirklich gebracht ... 
aber schau mal hier ...
https://www.reddit.com/r/Esphome/comments/119jy9o/esp32_ble_tracker_prevents_wifi_from_connecting/

**Comment by noone2k** [comment]
dieser issue ging um " Fehler in den Schaltern #2 " ....
und das ist behoben ?

**Comment by eshopsrc** [comment]
nein...


11:11:41 | [W] | [component:214] | Component esp32_ble took a long time for an operation (0.14 s).
-- | -- | -- | --
11:11:41 | [W] | [component:215] | Components should block for at most 20-30ms.
11:13:00 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:13:05 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)
11:13:10 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:13:15 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)
11:13:20 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:13:22 | [W] | [ble_sensor:078] | Error reading char at handle 24, status=2
11:13:22 | [W] | [ble_sensor:078] | Error reading char at handle 24, status=2
11:13:25 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)
11:13:30 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:13:35 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)
11:13:40 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:13:40 | [W] | [ble_sensor:078] | Error reading char at handle 21, status=2
11:13:40 | [W] | [ble_sensor:078] | Error reading char at handle 21, status=2
11:13:45 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)
11:13:50 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:13:55 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)
11:14:00 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:14:05 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)
11:14:10 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:14:15 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)
11:14:20 | [W] | [script:060] | Script 'ble_process' is already running! (mode: single)
11:14:22 | [W] | [ble_sensor:078] | Error reading char at handle 24, status=2
11:14:22 | [W] | [ble_sensor:078] | Error reading char at handle 24, status=2
11:14:25 | [W] | [script:060] | Script 'ble_process_cmd0F' is already running! (mode: single)

**Comment by noone2k** [comment]
ja, aber dieser issue in dem tracker ging um die schalter.
bei einem anderen issue, mach einen neuen auf.
pro fehler ein extra eintrag ... der ordnung halber ...
wenn jmd. jetzt nach nem fehler bei ble sucht aber nur die überschrift "fehler in schalter" liest, übersieht er das ggf.

**Comment by noone2k** [comment]
https://github.com/noone2k/hm2500pub/issues/2#issuecomment-1979277681
